### ISSUE TITLE
Default filter names issue / Azcam regex

### ISSUE THREAD

**Issue by davner** [so-mops/vatt-guidebox#22]
When the 4k gui is started, the default names of the filters are named with whitespace ie "Filter 1", "Filter 2". 

This is not handled correctly by the filter regex function in Azcam. We need to fix the regex function in Azcam.

There also seems to be some default filter naming scheme like a file. We need to find where these filters names are default and written and change it.

**Comment by srswinde** [comment]
Mike fixed this back in Oct. The fix must have been reverted. I can forward you the long email chain but there isn't any useful information in it. 

The file is saved with the [saveFNames function](https://github.com/so-mops/vatt-guidebox/blob/master/gb_indi.c#L2059). When I get time I will dig into when and how that file is written to.

**Comment by davner** [comment]
Mike fixed it on the AzCam side to handle white space in filter names?

**Comment by srswinde** [comment]
Yeah he made a regex fix. I just sent you the email thread. 

I looked at how saveFNames is used. Anytime the [lower](https://github.com/so-mops/vatt-guidebox/blob/master/gb_indi.c#L514) or [upper](https://github.com/so-mops/vatt-guidebox/blob/master/gb_indi.c#L530) filter names are changed it writes the file. In fact, there are two files, one for each wheel. The file names are the lower and upper filter wheel text property names. Those are defined [here](https://github.com/so-mops/vatt-guidebox/blob/master/gb_indi.c#L279). The name is the "LOWER_FNAMES" in the struct literal below.

```c
static ITextVectorProperty lfnTP = { mydev, "LOWER_FNAMES", "Lower Filter Wheel Names", MAIN_GROUP , IP_RW, 0, IPS_IDLE,  lfnT, NARRAY(lfnT), "", 0};
```
I am going to digress and explain this line because it confused the hell out of me the first time I saw it. Ignore this if you figured it out faster than I did. ITextVectorProperty is a C structure that is defined in indilib. There is a nice reference for it on the [indilib api page](https://www.indilib.org/api/struct__ITextVectorProperty.html). As you probably know, the `{}` characters denote an array (or struct in this case) literal. This is a way of declaring the `lfnTP` variable and assigning it in one line. The more common way to do this in C is to build a function that populates the struct. In fact, indilib has such a function. It is called IUFillTextVector. Both methods of filling the struct are used in gb_indi.c. 

I hope this helps. Let me know if you have any questions.

**Comment by davner** [comment]
Users can now enter in filters with spaces. We swapped the regex expression to

`
regex = re.compile('message="(\w*):(.+?(?=lower))(\w*):(.+?(?="))"')
`

This grabs the first word, upper, Then whatever is between the colon and "lower". Then grabs lower and then whatever follows the colon. 

Mike L and I tested it with filter names U and V in upper and lower. Then we tested it with "test 1 2 3" and "filter 1" in upper and lower and it worked fine. Filter names were written to the fits file.
